---
title: "Análisis y metodología estadística II"
subtitle: "Hipótesis nula (casi) no interpretable"
output:
  tufte::tufte_html: default
  tufte::tufte_handout: default
author: "Thomas Brochhagen"
date: "Última actualización: `r Sys.Date()`" 
---
```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

La idea detrás de *valores de p* es la de cuantificar una hypothesis a base de la improbabiliad de otra. Puede que esto suene un poco contraintuitivo. No por nada *significancia estadística* y *valores de p* son, hoy en día, un tema controversial -- tanto porque hay métodos más adecuados (ver abajo) como porque mucha gente, expertos y no-expertos, malentienden lo que se está cuantificando.

* Hypothesis nula

En esencia, significancia estadística requiere una hypothesis nula. La idea no es probar que esta hypothesis sea correcta (probable). En general, se quiere mostrar que es incorrecta (improbable), así que en general no corresponde a la intuición del experimentador. Si la hipotesis que queremos demostrar es que la pobreza disminuyó del *2015* al *2017*, la idea sería demostrar que es improbable que los resultados de la encuesta para el *2015* y *2017* fueran como lo son asumiendo que "no disminuyó la pobreza" (la famosa hipótesis nula). 

Recopilando: Queremos saber si hay un cambio real en el mundo, por ejemplo, disminución de pobreza. Nuestra encuesta no refleja el mundo real por muchas razones. Por ejemplo, no todo el mundo fue encuestado. No podemos decir con certeza si hay un cambio real así que la metodología empleada por los analístas de la encuesta nos pide preguntarnos ¿Cuál es la probabilidad de encontrar una diferencia igual o mayor que la encontrada entre el *2015* y el *2017* asumiendo que la hipotesis nula es correcta? 

Osea, aplicada al caso de la pobreza, la idea es cuantificar la probabilidad de un resultado de encuesta igual o más pronunciado si volvieramos a pasar la encuesta. Hablamos de *valores de p* en relación a tests de significancia porque son un valor arbitrario^[Nota historica] a partir del cual 

https://andrewgelman.com/2013/03/12/misunderstanding-the-p-value/
http://pb204.blogspot.com/2012/07/bunhill-fields.html
http://www.stat.columbia.edu/~gelman/research/published/pvalues3.pdf
http://www.stat.columbia.edu/~gelman/research/published/jasa_signif_2.pdf
http://www.stat.columbia.edu/~gelman/research/unpublished/abandon.pdf

---
# Indice temático y links
## [Introducción](../main.html)
## Visualización 
* [Ejes que engañan](./01ejes.html)
* [Gráficos circulares](./02pie-charts.html)
* [Tablas que agrupan lo in-agrupable](./03tablas)

## Análisis y metodología estadística
* [Estimados de puntos y perdida de información](./04point-estimates.html)
* Hipótesis nula (casi) no interpretable
* [El coeficiente Gini](./06gini.html)
