---
title: "La encuesta Casen 2017"
subtitle: "Introducción"
output:
  tufte::tufte_html: default
  tufte::tufte_handout: default
author: "Thomas Brochhagen"
date: "Última actualización: `r Sys.Date()`" 
---
```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

El 21 de Agosto se presentaron los resultados de la encuesta Casen 2017. Esta encuesta es una de las principales caracterizaciones de desarrollos socio-económicos en Chile.^[La presentación, los resultados, la metodología, y los cuestionarios utilizados están publicados en la página web del [Ministerio de Desarrollo Social ](http://observatorio.ministeriodesarrollosocial.gob.cl), quien mandata la encuesta.] Busca cuantificar temas importantes como la evolución de la pobreza en el país ¿Estamos peor, mejor, o igual que antes? Por su importancia muchas decisiones políticas se basan en esta encuesta.

Los detalles de la encuesta dan para mucha discusión.^[Por ejemplo, la manera en la que se calcúla la pobreza monetaria, como discute [un reciente artículo de la Fundación SOL](http://www.fundacionsol.cl/2018/09/las-trampas-del-famoso-alquiler-imputado/).] Aquí solo quiero enfocarme, menos ambiciosamente, en como se [presentaron los resultados](http://observatorio.ministeriodesarrollosocial.gob.cl/casen-multidimensional/casen/docs/Presentacion_Sintesis_de_Resultados_Casen_2017.pdf) al publico. Ojalá de esto algo se pueda aprender, tanto sobre los resultados de este año, como para futuros levantamientos, su presentación, y su crítica recepción. 

Enfocarse en la presentación del 21 de Agosto no es solamente conveniente por ser más corta que el informe completo. También me motiva la suposición que la mayoría de la gente solo ve e interpreta esta particular versión de los resultados.

Hay seis aspectos que llaman la atención. Tres tienen que ver con como se presentan los resultados *visualmente*; los otros tres tienen más que ver con el *análisis* y la *metodología* que se usan. En todos los casos la discusión se basará en temáticas ya conocidas hace decadas en areas de estadística y visualización. No diré nada nuevo en este sentido. La idea es aprender que tipo de aspectos de un análisis y su presentación pueden ser llamativos para, últimamente, formar una visión más crítica y difícil de manipular.

# Indice temático y links
## Visualización 
* [Ejes que engañan](./content/01ejes.html)
* [Gráficos circulares](./content/02pie-charts.html)
* [Tablas que agrupan lo incomparable](./content/03tablas.html)

## Análisis y metodología estadística
* [Estimados de puntos y perdida de información](./content/04point-estimates.html)
* [Hipótesis nula (casi) no interpretable](./content/05nht.html)
* [El Coeficiente de Gini](./content/06gini.html)

# Conclusión
Resumiendo, algunos problemas son menores (gráficos cirulares), otros son más severos (hipótesis nula; estimados de puntos; ejes; tablas), y otros requieren un trasfondo crítico que puede faltarle a la audiencia (coeficiente Gini). 

Lo que más llama la atención es que, aparte del último punto, todos estos problemas son conocidos y fáciles de evitar. Que aparezcan en un informe tan importante sugiere que los organismos involucrados tienen que hacer mejor sus tareas -- si su intensión es informar. También vale la pena parar a reflexionar sobre la intensión detrás de torcidas de datos que sugieren mensajes políticos que los datos no apoyan.